version: '3.7'

services:
  logstash:
    depends_on:
      - couchdb
      - elasticsearch

  couchdb:
    image: couchdb
    restart: always
    volumes:
      - ./couchdb:/opt/couchdb/etc/local.d/
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}

  bootstrap:
    image: curlimages/curl
    depends_on:
      - couchdb
    command: -X PUT http://${COUCHDB_USER}:${COUCHDB_PASSWORD}@couchdb:5984/${COUCHDB_DB}
    restart: on-failure:5

  bootstrap_users:
    image: curlimages/curl
    depends_on:
      - couchdb
    command: -X PUT http://${COUCHDB_USER}:${COUCHDB_PASSWORD}@couchdb:5984/_users
    restart: on-failure:5